### ISSUE TITLE
"EOF while parsing a value" if NIXOS_CHANNELS env variable is empty

### ISSUE THREAD

**Issue by alex-fu27** [NixOS/nixos-search#585]
If I run `flake-info nixpkgs nixos-22.11`, I expect `flake-info` to use the official nixpkgs repo as the help text says and to use the `nixos-22.11` branch. However, I get
```plain
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/bin/flake-info.rs:443:10
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-1.64.0-src/library/core/src/result.rs:1107:23
   4: <flake_info::NIXOS_CHANNELS as core::ops::deref::Deref>::deref::__static_ref_initialize
             at ./src/bin/flake-info.rs:440:48
   5: core::ops::function::FnOnce::call_once
             at /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
   6: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:31:29
   7: std::sync::once::Once::call_once::{{closure}}
             at /build/rustc-1.64.0-src/library/std/src/sync/once.rs:276:41
   8: std::sync::once::Once::call_inner
   9: std::sync::once::Once::call_once
             at /build/rustc-1.64.0-src/library/std/src/sync/once.rs:276:9
  10: lazy_static::lazy::Lazy<T>::get
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:30:9
  11: <flake_info::NIXOS_CHANNELS as core::ops::deref::Deref>::deref::__stability
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:142:21
  12: <flake_info::NIXOS_CHANNELS as core::ops::deref::Deref>::deref
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs:144:17
  13: flake_info::run_command::{{closure}}
             at ./src/bin/flake-info.rs:228:13
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-1.64.0-src/library/core/src/future/mod.rs:91:19
  15: flake_info::main::{{closure}}
             at ./src/bin/flake-info.rs:170:75
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /build/rustc-1.64.0-src/library/core/src/future/mod.rs:91:19
  17: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/park/thread.rs:263:54
  18: tokio::coop::with_budget::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:106:9
  19: std::thread::local::LocalKey<T>::try_with
             at /build/rustc-1.64.0-src/library/std/src/thread/local.rs:445:16
  20: std::thread::local::LocalKey<T>::with
             at /build/rustc-1.64.0-src/library/std/src/thread/local.rs:421:9
  21: tokio::coop::with_budget
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:99:5
  22: tokio::coop::budget
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/coop.rs:76:5
  23: tokio::park::thread::CachedParkThread::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/park/thread.rs:263:31
  24: tokio::runtime::enter::Enter::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/enter.rs:151:13
  25: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/thread_pool/mod.rs:72:9
  26: tokio::runtime::Runtime::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.11.0/src/runtime/mod.rs:459:43
  27: flake_info::main
             at ./src/bin/flake-info.rs:185:5
  28: core::ops::function::FnOnce::call_once
             at /build/rustc-1.64.0-src/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Because in case `NIXOS_CHANNELS` is unset, the block
```rust
lazy_static! {
    static ref NIXOS_CHANNELS: NixosChannels = std::env::var("NIXOS_CHANNELS")
        .unwrap_or("".to_string())
        .parse()
        .unwrap();
}
```
replaces it with `""`, which can't be parsed as JSON by Serde.

Edit: fix markdown

**Comment by ncfavier** [comment]
Thanks, the NIXOS_CHANNELS logic in flake-info is completely broken anyway, I was planning to fix it soon.

Out of curiosity, how are you running flake-info? NIXOS_CHANNEL should be set in the `devShell`, and it's set in the wrapper if you just `nix run nixos-search`.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nixos-search/pull/586

**Comment by alex-fu27** [comment]
I'm new to Nix(OS) so I am trying to avoid Flakes and everything called "experimental". But I found a `default.nix` in the `flake-info` dir, so I just did a `nix-shell` there and called `cargo run`.
